name: 💡 Feature Request
description: Suggest an idea for this project.
title: "[FEATURE] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        **Please describe the feature request:**
        A clear and concise description of what the feature is and why you think it should be added.
  
  - type: textarea
    attributes:
      label: Use Case
      description: "Explain the use case for this feature. Why would this feature be valuable to you or others?"
      placeholder: "The specific problem or need that this feature addresses."
  
  - type: textarea
    attributes:
      label: Proposed Solution
      description: "Describe how you envision this feature being implemented. If applicable, provide examples or diagrams."
      placeholder: "A brief description or suggestion for how the feature could be implemented."
  
  - type: textarea
    attributes:
      label: Additional Information
      description: "Include any additional information, context, or related links."
      placeholder: "Any additional context or details."
