name: 🔧 Code Improvement
description: Suggest code improvements or refactorings.
title: "[IMPROVEMENT] "
labels:
  - refactoring
  - improvement
body:
  - type: markdown
    attributes:
      value: |
        **Please describe the improvement:**
        A clear and concise description of the code improvement or refactoring you're suggesting.
  
  - type: textarea
    attributes:
      label: Current Code Issue
      description: "Describe the problem with the current implementation (e.g., performance, readability, complexity)."
      placeholder: "The issue or inefficiency with the current code."
  
  - type: textarea
    attributes:
      label: Suggested Improvement
      description: "Describe your proposed solution or improvement."
      placeholder: "Details of the suggested improvement or refactoring."
  
  - type: textarea
    attributes:
      label: Impact
      description: "Explain the impact or benefit of making this improvement (e.g., improved performance, better maintainability)."
      placeholder: "How this change will benefit the project."
  
  - type: textarea
    attributes:
      label: Additional Information
      description: "Include any additional information, context, or related links."
      placeholder: "Any additional context or details."
